# Generated by Django 5.1.4 on 2025-01-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0004_alter_billingdetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Delivered', max_length=50),
        ),
    ]
